name: Bal push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Docker build
      run: |
        wget https://dist.ballerina.io/downloads/2201.2.0/ballerina-2201.2.0-swan-lake.zip
        docker build --build-arg BALLERINA_DIST="ballerina-2201.2.0-swan-lake.zip" -t xlight05/ballerina-test:1 .
        docker push xlight05/ballerina-test:1
