name: Bal push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Docker build
      run: |
        wget https://github.com/ballerina-platform/ballerina-distribution/releases/download/v2201.2.1-rc1/ballerina-2201.2.1-swan-lake-linux-x64.deb
        sudo dpkg -i ballerina-2201.2.1-swan-lake-linux-x64.deb
        cd bbe && bal build && cat target/docker/bbe/Dockerfile
        docker images
        docker run -d -p 9090:9090 bbe:latest
        sleep 5
        docker tag bbe:latest xlight05/bbe:latest 
        docker push xlight05/bbe:latest 
        curl http://localhost:9090/helloWorld/sayHello
        docker ps
