name: Build and Push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Docker build
      run: |
        docker build -t xlight05/mandren-http:latest .
        docker push xlight05/mandren-http:latest
    - name: Docker Run
      run: |
        docker run -d -p 9090:9090 xlight05/mandren-http:latest
        docker ps
        curl http://localhost:9090/greeting
